cmeError = {
    0:"phone failure",
    1:"no connection to phone",
    2:"phone adaptor link reserved",
    3:"operation not allowed",
    4:"operation not supported",
    5:"PH SIM PIN required",
    6:"PH-FSIM PIN required",
    7:"PH-FSIM PUK required",
    10:"SIM not inserted",
    11:"SIM PIN required",
    12:"SIM PUK required",
    13:"SIM failure",
    14:"SIM busy",
    15:"SIM wrong",
    16:"incorrect password",
    17:"SIM PIN2 required",
    18:"SIM PUK2 required",
    20:"memory full",
    21:"invalid index",
    22:"not found",
    23:"memory failure",
    24:"text string too long",
    25:"invalid characters in text string",
    26:"dial string too long",
    27:"invalid characters in dial string",
    30:"no network service",
    31:"network timeout",
    32:"network not allowed - emergency calls only",
    40:"network personalization PIN required",
    41:"network personalization PUK required",
    42:"network subset personalization PIN required",
    43:"network subset personalization PUK required",
    44:"service provider personalization PIN required",
    45:"service provider personalization PUK required",
    46:"corporate personalization PIN required",
    47:"corporate personalization PUK required",
    48:" Key for personalization already exists",
    100:"unknown",
    103:"Illegal MS (#3)",
    106:"Illegal ME (#6)",
    107:"GPRS services not allowed (#7)",
    111:"PLMN not allowed (#11)",
    112:"Location area not allowed (#12)",
    113:"Roaming not allowed in this location area (#13)",
    132:"service option not supported (#32)",
    133:"requested service option not subscribed (#33)",
    134:"service option temporarily out of order (#34)",
    149:"PDP authentication failure",
    150:"invalid mobile class",
    148:"unspecified GPRS error",
    151:"VBS/VGCS not supported by the network",
    152:"No service subscription on SIM",
    153:"No subscription for group ID",
    154:"Group Id not activated on SIM",
    155:"No matching notification",
    156:"VBS/VGCS call already present",
    157:"Congestion",
    158:"Network failure",
    159:"Uplink busy",
    160:"No access rights for SIM file ",
    161:"No subscription for priority",
    162:"operation not applicable or not possible"}
    
cmsError ={321:"Invalid memory index",
322:"Memory Full",
340:"No +CNMA acknowledgement expected",
302:"Operation not allowed",
300:"ME Failure",
313:"SIM Failure",
315:"SIM Wrong",
320:"Memory failure",
38:"Network out of order",
194:"SC system failure",
128:"Telematic internetworking not supported",
21:"Short message transfer rejected",
29:"Facility rejected",
50:"Requested facility not subscribed",
69:"Requested facility not implemented",
129:"Short message type 0 not supported",
130:"Cannot replace short message",
143:"Unspecified TP-PID error",
144:"Data coding scheme (alphabet) not supported",
145:"Message class not supported",
159:"Unspecified TP-DCS error",
176:"TPDU not supported",
198:"TP-VPF not supported",
199:"TP-VP not supported",
303:"Operation not supported",
514:"Invalid character set",
97:"Message type non existent or not implemented",
866:"Message type not compatible with call state or message type…",
98:"Message not compatible with short message protocol state",
99:"Information element non existent or not implemented",
81:"Invalid short message reference value",
95:"Invalid message, unspecified",
304:"Invalid PDU mode parameter",
305:"Invalid TEXT mode parameter",
863:"Invalid message",
868:"Invalid information element contents",
1887:"Semantically incorrect message",
96:"Invalid mandatory information",
310:"SIM not inserted",
193:"No SC subscription",
331:"No network service",
33552:"Cell selection failed",
33825:"MS is not registered",
311:"SIM PIN required",
312:"PH-SIM PIN required",
316:"SIM PUK required",
317:"SIM PIN2 required",
318:"SIM PUK2 required",
1:"Unassigned (unallocated) number",
27:"Destination out of service",
28:"Unidentified subscriber",
30:"Unknown subscriber",
195:"Invalid SME address",
8:"Operator determined barring",
515:"Number not in FDN",
10:"Call Barred",
196:"Destination SME barred",
33568:"Access barred because of access class control",
330:"SMSC address unknown",
197:"SM Rejected-Duplicate SM",
41:"Temporary failure",
47:"Resources unavailable, unspecified",
111:"Protocol error, unspecified",
127:"Internetworking, unspecified",
255:"Unspecified error cause",
500:"Unknown error",
513:"Need to reset ACM",
768:"Normal release",
769:"Abnormal release, unspecified",
770:"Abnormal release, channel unacceptable",
771:"Abnormal release, timer expired",
772:"Abnormal release, no activity on radio path",
833:"Call already cleared",
1809:"Network failure",
1873:"Invalid transaction identifier",
33553:"Radio link failure",
33554:"Internal protocol error",
33555:"Data link failure",
33570:"Random access failed",
33571:"DL establishment failure",
33572:"RR failure",
33824:"Unspecified release by MM",
332:"Network timeout",
33826:"Time-out in MM during establishment",
42:"Congestion",
192:"SC busy",
33569:"Random access delayed (immediate assignment reject)",
301:"SMS service of ME reserved",
314:"SIM busy",
517:"SMS service access collision",
773:"Preemptive release",
33573:"Collision MO with MT, MT has higher priority than MO"}